//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interprete.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interprete.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comando BREAK insertará un punto de interrupción dentro del
        ///código, si está siendo depurado por un depurador..
        /// </summary>
        internal static string _break {
            get {
                return ResourceManager.GetString("_break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra el nombre del directorio actual o cambia de directorio.
        ///
        ///CHDIR [/D] [unidad:][ruta]
        ///CHDIR [..]
        ///CD [/D] [unidad:][ruta]
        ///CD [..]
        ///
        ///  ..   Especifica que desea cambiar al directorio superior.
        ///
        ///Si las extensiones de comando están habilitadas, CHDIR cambia así:
        ///
        ///El uso de mayúsculas y minúsculas de la cadena del directorio actual se
        ///convierte al mismo uso que se tiene en los nombres de unidades. Así, CD
        ///C:\TEMP establecerá C:\Temp como el directorio actual si éste es el uso
        ///de mayúsculas y m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cd {
            get {
                return ResourceManager.GetString("cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borra la pantalla.
        ///
        ///CLS.
        /// </summary>
        internal static string cls {
            get {
                return ResourceManager.GetString("cls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia una nueva instancia del intérprete de comandos de Windows
        ///
        ///
        ///CMD.
        /// </summary>
        internal static string cmd {
            get {
                return ResourceManager.GetString("cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configura los colores predeterminados de primer y segundo plano de la consola.
        ///
        ///COLOR [attr]
        ///
        ///  attr         Especifica el atributo de color de la salida de consola.
        ///
        ///Los atributos de color están especificados con DOS dígitos hexadecimales (el primero
        ///corresponde al segundo plano; el segundo al primer plano). Los dígitos
        ///pueden coincidir con cualquiera de los siguientes valores:
        ///
        ///    0 = Negro       8 = Gris
        ///    1 = Azul        9 = Azul claro
        ///    2 = Verde       A = Verde claro
        ///    3 = Aguamari [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia uno o más archivos en otra ubicación.
        ///
        ///COPY [/Y | /-Y] origen destino
        ///
        ///  origen       Especifica el archivo o archivos que deben copiarse.
        ///  destino      Especifica el directorio y/o el nombre de archivo de los
        ///               nuevos archivos.
        ///  /Y           Suprime la solicitud de confirmación antes de
        ///               sobrescribir un archivo de destino existente.
        ///  /-Y          Solicita confirmación antes de sobrescribir un archivo de
        ///               destino existente.
        ///.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra la lista de subdirectorios y archivos de un directorio.
        ///
        ///DIR [unidad:][ruta][archivo] [/B] [/L] [/P]
        ///
        ///  [unidad:][ruta][nombre de archivo]
        ///              Especifica la unidad, el directorio y los archivos que se
        ///              mostrarán.
        ///
        ///  /B          Usa el formato simple (sin encabezados ni sumarios).
        ///  /L          Usa letras minúsculas.
        ///  /N          Nuevo formato de lista larga donde los nombre de archivo aparecen
        ///              en el lado derecho.
        ///  /P          Hace una pausa después  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra mensajes o activa y desactiva el eco del comando.
        ///
        ///  ECHO [ON | OFF]
        ///  ECHO [message]
        ///
        ///Escribe ECHO sin parámetros para mostrar la configuración actual del eco..
        /// </summary>
        internal static string echo {
            get {
                return ResourceManager.GetString("echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina uno o más archivos.
        ///
        ///DEL [/P] nombres
        ///ERASE [/P] nombres
        ///
        ///  nombres       Especifica una lista de uno o más archivos o directorios.
        ///                Se puede usar comodines para eliminar varios archivos.
        ///                Si se especifica un directorio, todos sus archivos se
        ///                eliminarán.
        ///
        ///  /P            Pide confirmación antes de eliminar cada archivo..
        /// </summary>
        internal static string erase {
            get {
                return ResourceManager.GetString("erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandona el programa CMD.EXE (intérprete de comandos) o el script
        ///por lotes actual.
        ///
        ///EXIT.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para obtener más información acerca de un comando específico, escriba HELP
        ///seguido del nombre de comando
        ///
        ///BREAK          Genera una interrupción del sistema.
        ///CD             Muestra el nombre del directorio actual o cambia a otro
        ///               directorio.
        ///CLS            Borra la pantalla.
        ///CMD            Inicia una nueva instancia del intérprete de comandos.
        ///COLOR          Establece los colores de primer plano y fondo predeterminados
        ///               de la consola.
        ///COPY           Copia uno o más arch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string generalHelp {
            get {
                return ResourceManager.GetString("generalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporciona información de ayuda para los comandos de Windows.
        ///
        ///HELP [comando]
        ///
        ///    comando - muestra información de ayuda del comando especificado..
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra el nombre del host actual.
        ///
        ///hostname.
        /// </summary>
        internal static string hostname {
            get {
                return ResourceManager.GetString("hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea un directorio.
        ///
        ///MKDIR [unidad:]ruta
        ///MD [unidad:]ruta
        ///
        ///Si las extensiones de comandos están habilitadas, MKDIR cambia así:
        ///
        ///MKDIR crea cualquier directorio intermedio de la ruta de acceso siempre
        ///que sea necesario. Por ejemplo, si \a no existe:
        ///
        ///    mkdir \a\b\c\d
        ///
        ///es lo mismo que:
        ///
        ///    mkdir \a
        ///    chdir \a
        ///    mkdir b
        ///    chdir b
        ///    mkdir c
        ///    chdir c
        ///    mkdir d.
        /// </summary>
        internal static string md {
            get {
                return ResourceManager.GetString("md", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mueve archivos y cambia el nombre a archivos y directorios.
        ///
        ///Mover uno o más archivos:
        ///MOVE [/Y | /-Y] [unidad:][ruta]nombrearchivo1 destino
        ///
        ///
        ///  destino            Especifica la nueva ubicación del archivo. El
        ///                     destino puede constar de una letra de unidad y
        ///                     dos puntos, un nombre de directorio o una
        ///                     combinación. Si mueve solo un archivo, también
        ///                     puede incluir un nombre de archivo si quiere
        ///                     cambi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string move {
            get {
                return ResourceManager.GetString("move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspende el proceso de un programa por lotes y muestra el mensaje
        ///    Presione una tecla para continuar. . ..
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia al directorio guardado por el comando PUSHD.
        ///
        ///POPD.
        /// </summary>
        internal static string popd {
            get {
                return ResourceManager.GetString("popd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarda el directorio actual para que lo use el comando POPD y después
        ///cambia al directorio especificado.
        ///
        ///PUSHD [ruta | ..]
        ///
        /// ruta        Especifica el directorio al que hay que cambiar el actual..
        /// </summary>
        internal static string pushd {
            get {
                return ResourceManager.GetString("pushd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quita (elimina) un directorio.
        ///
        ///RMDIR [/S] [/Q] [unidad:]ruta
        ///RD [/S] [/Q] [unidad:]ruta.
        /// </summary>
        internal static string rd {
            get {
                return ResourceManager.GetString("rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia el nombre de uno o más archivos.
        ///
        ///RENAME [unidad:][ruta]archivo1 archivo2.
        ///REN [unidad:][ruta]archivo1 archivo2..
        /// </summary>
        internal static string ren {
            get {
                return ResourceManager.GetString("ren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fija el título de la ventana en la ventana del símbolo del sistema.
        ///
        ///TITLE [cadena]
        ///
        /// cadena    Especifica el título de la ventana del símbolo del sistema..
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra la versión del interprete
        ///
        ///VER.
        /// </summary>
        internal static string ver {
            get {
                return ResourceManager.GetString("ver", resourceCulture);
            }
        }
    }
}
